/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user.etalase.topi;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import kaweshop.Kaweshop;

/**
 *
 * @author KWHY
 */
public class sombrero extends javax.swing.JPanel {

    /**
     * Creates new form sombrero
     */
    public String id1;
    public String id2;
    public String id3;
    public String nama1;
    public String nama2;
    public String nama3;
    public String harga1;
    public String harga2;
    public String harga3;
    public sombrero() {
        initComponents();
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 19;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id1 = r.getString("id_barang");
                nama1 = r.getString("nama_barang");
                harga1 = r.getString("harga");
  
                namasombrero1.setText(nama1.toUpperCase());
                hargasombrero1.setText("Rp."+harga1);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 20;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id2 = r.getString("id_barang");
                nama2 = r.getString("nama_barang");
                harga2 = r.getString("harga");
  
                namasombrero2.setText(nama2.toUpperCase());
                hargasombrero2.setText("Rp."+harga2);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 21;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id3 = r.getString("id_barang");
                nama3 = r.getString("nama_barang");
                harga3 = r.getString("harga");
  
                namasombrero3.setText(nama3.toUpperCase());
                hargasombrero3.setText("Rp."+harga3);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        namasombrero3 = new javax.swing.JLabel();
        namasombrero1 = new javax.swing.JLabel();
        namasombrero2 = new javax.swing.JLabel();
        hargasombrero3 = new javax.swing.JTextField();
        hargasombrero1 = new javax.swing.JTextField();
        hargasombrero2 = new javax.swing.JTextField();
        jumlahsombrero1 = new javax.swing.JTextField();
        jumlahsombrero2 = new javax.swing.JTextField();
        jumlahsombrero3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 77, 168));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(42, 186, 237));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sombrero-Hat-Transparent-PNG.png"))); // NOI18N
        jPanel19.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 225, 294));

        jSeparator1.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator1.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 225, 10));

        jPanel20.setBackground(new java.awt.Color(42, 186, 237));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-hat-headgear-sombrero-cap-yellow-bamboo-hat-5aacc71ee407d3.349590961521272606934.png"))); // NOI18N
        jPanel20.add(jLabel3, java.awt.BorderLayout.CENTER);

        add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 225, 294));

        jPanel21.setBackground(new java.awt.Color(42, 186, 237));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pngwing.com (5)_1.png"))); // NOI18N
        jPanel21.add(jLabel2, java.awt.BorderLayout.CENTER);

        add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 225, 294));

        jSeparator2.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator2.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 230, -1));

        jSeparator3.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator3.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 230, 10));

        namasombrero3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namasombrero3.setForeground(new java.awt.Color(42, 186, 237));
        namasombrero3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namasombrero3.setText("Topi Sombrero 3");
        add(namasombrero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 230, -1));

        namasombrero1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namasombrero1.setForeground(new java.awt.Color(42, 186, 237));
        namasombrero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namasombrero1.setText("Topi Sombrero 1");
        add(namasombrero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, -1));

        namasombrero2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namasombrero2.setForeground(new java.awt.Color(42, 186, 237));
        namasombrero2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namasombrero2.setText("Topi Sombrero 2");
        add(namasombrero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 230, -1));

        hargasombrero3.setBackground(new java.awt.Color(16, 77, 168));
        hargasombrero3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargasombrero3.setForeground(new java.awt.Color(255, 255, 255));
        hargasombrero3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargasombrero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 230, -1));

        hargasombrero1.setBackground(new java.awt.Color(16, 77, 168));
        hargasombrero1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargasombrero1.setForeground(new java.awt.Color(255, 255, 255));
        hargasombrero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargasombrero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 230, -1));

        hargasombrero2.setBackground(new java.awt.Color(16, 77, 168));
        hargasombrero2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargasombrero2.setForeground(new java.awt.Color(255, 255, 255));
        hargasombrero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargasombrero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 230, -1));

        jumlahsombrero1.setBackground(new java.awt.Color(16, 77, 168));
        jumlahsombrero1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        add(jumlahsombrero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 100, 40));

        jumlahsombrero2.setBackground(new java.awt.Color(16, 77, 168));
        jumlahsombrero2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        add(jumlahsombrero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, 40));

        jumlahsombrero3.setBackground(new java.awt.Color(16, 77, 168));
        jumlahsombrero3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        add(jumlahsombrero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 100, 40));

        jButton5.setBackground(new java.awt.Color(16, 77, 168));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 40, -1));

        jButton6.setBackground(new java.awt.Color(16, 77, 168));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 40, -1));

        jButton10.setBackground(new java.awt.Color(16, 77, 168));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String jmlhsombrero3= jumlahsombrero3.getText();
        int jmlh = Integer.parseInt(jmlhsombrero3);
        int hrg3 = Integer.parseInt(harga3);
        int totalharga = jmlh * hrg3;
        String jmlhharga = Integer.toString(totalharga);
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id3);
            p.setString(2, nama3);
            p.setString(3, harga3);
            p.setString(4, jmlhsombrero3);
            p.setString(5, jmlhharga);
            p.executeUpdate();
            p.close();
        }catch(SQLException ex){
            System.out.println("erur");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String jmlhsombrero1= jumlahsombrero1.getText();
        int jmlh = Integer.parseInt(jmlhsombrero1);
        int hrg1 = Integer.parseInt(harga1);
        int totalharga = jmlh * hrg1;
        String jmlhharga = Integer.toString(totalharga);
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id1);
            p.setString(2, nama1);
            p.setString(3, harga1);
            p.setString(4, jmlhsombrero1);
            p.setString(5, jmlhharga);
            p.executeUpdate();
            p.close();
        }catch(SQLException ex){
            System.out.println("erur");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String jmlhsombrero2= jumlahsombrero2.getText();
        int jmlh = Integer.parseInt(jmlhsombrero2);
        int hrg2 = Integer.parseInt(harga2);
        int totalharga = jmlh * hrg2;
        String jmlhharga = Integer.toString(totalharga);
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id2);
            p.setString(2, nama2);
            p.setString(3, harga2);
            p.setString(4, jmlhsombrero2);
            p.setString(5, jmlhharga);
            p.executeUpdate();
            p.close();
        }catch(SQLException ex){
            System.out.println("erur");
        }
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargasombrero1;
    private javax.swing.JTextField hargasombrero2;
    private javax.swing.JTextField hargasombrero3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jumlahsombrero1;
    private javax.swing.JTextField jumlahsombrero2;
    private javax.swing.JTextField jumlahsombrero3;
    private javax.swing.JLabel namasombrero1;
    private javax.swing.JLabel namasombrero2;
    private javax.swing.JLabel namasombrero3;
    // End of variables declaration//GEN-END:variables
}
