/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user.etalase.topi;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import kaweshop.Kaweshop;

/**
 *
 * @author KWHY
 */
public class topijeramii extends javax.swing.JPanel {

    /**
     * Creates new form topijerami
     */
    public String id1;
    public String id2;
    public String id3;
    public String nama1;
    public String nama2;
    public String nama3;
    public String harga1;
    public String harga2;
    public String harga3;
    public topijeramii() {
        initComponents();
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 25;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id1 = r.getString("id_barang");
                nama1 = r.getString("nama_barang");
                harga1 = r.getString("harga");
  
                namatopijerami1.setText(nama1.toUpperCase());
                hargajerami1.setText("Rp."+harga1);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 26;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id2 = r.getString("id_barang");
                nama2 = r.getString("nama_barang");
                harga2 = r.getString("harga");
  
                namatopijerami2.setText(nama2.toUpperCase());
                hargajerami2.setText("Rp."+harga2);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 27;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id3 = r.getString("id_barang");
                nama3 = r.getString("nama_barang");
                harga3 = r.getString("harga");
  
                namatopijerami3.setText(nama3.toUpperCase());
                hargajerami3.setText("Rp."+harga3);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        namatopijerami3 = new javax.swing.JLabel();
        namatopijerami1 = new javax.swing.JLabel();
        namatopijerami2 = new javax.swing.JLabel();
        hargajerami3 = new javax.swing.JTextField();
        hargajerami1 = new javax.swing.JTextField();
        hargajerami2 = new javax.swing.JTextField();
        jumlahjerami1 = new javax.swing.JTextField();
        jumlahjerami2 = new javax.swing.JTextField();
        jumlahjerami3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 77, 168));

        jPanel19.setBackground(new java.awt.Color(42, 186, 237));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-straw-hat-sun-hat-headgear-fedora-5b38bba87b16a3.5833419415304447125042.png"))); // NOI18N
        jPanel19.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel20.setBackground(new java.awt.Color(42, 186, 237));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pngwing.com (5).png"))); // NOI18N
        jPanel20.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel21.setBackground(new java.awt.Color(42, 186, 237));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jeramitopi.png"))); // NOI18N
        jPanel21.add(jLabel1, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator1.setForeground(new java.awt.Color(42, 186, 237));

        jSeparator3.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator3.setForeground(new java.awt.Color(42, 186, 237));

        jSeparator4.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator4.setForeground(new java.awt.Color(42, 186, 237));

        namatopijerami3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namatopijerami3.setForeground(new java.awt.Color(42, 186, 237));
        namatopijerami3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namatopijerami3.setText("Topi Jerami 3");

        namatopijerami1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namatopijerami1.setForeground(new java.awt.Color(42, 186, 237));
        namatopijerami1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namatopijerami1.setText("Topi Jerami 1");

        namatopijerami2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namatopijerami2.setForeground(new java.awt.Color(42, 186, 237));
        namatopijerami2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namatopijerami2.setText("Topi Jerami 2");

        hargajerami3.setBackground(new java.awt.Color(16, 77, 168));
        hargajerami3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargajerami3.setForeground(new java.awt.Color(255, 255, 255));
        hargajerami3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        hargajerami1.setBackground(new java.awt.Color(16, 77, 168));
        hargajerami1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargajerami1.setForeground(new java.awt.Color(255, 255, 255));
        hargajerami1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        hargajerami2.setBackground(new java.awt.Color(16, 77, 168));
        hargajerami2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargajerami2.setForeground(new java.awt.Color(255, 255, 255));
        hargajerami2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jumlahjerami1.setBackground(new java.awt.Color(16, 77, 168));
        jumlahjerami1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        jumlahjerami2.setBackground(new java.awt.Color(16, 77, 168));
        jumlahjerami2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        jumlahjerami3.setBackground(new java.awt.Color(16, 77, 168));
        jumlahjerami3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        jButton6.setBackground(new java.awt.Color(16, 77, 168));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(16, 77, 168));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(16, 77, 168));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahjerami1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namatopijerami1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(hargajerami1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(namatopijerami2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(hargajerami2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahjerami2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(namatopijerami3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargajerami3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahjerami3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namatopijerami2)
                            .addComponent(namatopijerami3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargajerami2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargajerami3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namatopijerami1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargajerami1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahjerami2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jumlahjerami1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jumlahjerami3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String jmlhjerami1= jumlahjerami1.getText();
        int jmlh = Integer.parseInt(jmlhjerami1);
        int hrg1 = Integer.parseInt(harga1);
        int totalharga = jmlh * hrg1;
        String jmlhharga = Integer.toString(totalharga);
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id1);
            p.setString(2, nama1);
            p.setString(3, harga1);
            p.setString(4, jmlhjerami1);
            p.setString(5, jmlhharga);
            p.executeUpdate();
            p.close();
        }catch(SQLException ex){
            System.out.println("erur");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String jmlhjerami2= jumlahjerami2.getText();
        int jmlh = Integer.parseInt(jmlhjerami2);
        int hrg2 = Integer.parseInt(harga2);
        int totalharga = jmlh * hrg2;
        String jmlhharga = Integer.toString(totalharga);
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id2);
            p.setString(2, nama2);
            p.setString(3, harga2);
            p.setString(4, jmlhjerami2);
            p.setString(5, jmlhharga);
            p.executeUpdate();
            p.close();
        }catch(SQLException ex){
            System.out.println("erur");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String jmlhjerami3= jumlahjerami3.getText();
        int jmlh = Integer.parseInt(jmlhjerami3);
        int hrg3 = Integer.parseInt(harga3);
        int totalharga = jmlh * hrg3;
        String jmlhharga = Integer.toString(totalharga);
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id3);
            p.setString(2, nama3);
            p.setString(3, harga3);
            p.setString(4, jmlhjerami3);
            p.setString(5, jmlhharga);
            p.executeUpdate();
            p.close();
        }catch(SQLException ex){
            System.out.println("erur");
        }
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargajerami1;
    private javax.swing.JTextField hargajerami2;
    private javax.swing.JTextField hargajerami3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jumlahjerami1;
    private javax.swing.JTextField jumlahjerami2;
    private javax.swing.JTextField jumlahjerami3;
    private javax.swing.JLabel namatopijerami1;
    private javax.swing.JLabel namatopijerami2;
    private javax.swing.JLabel namatopijerami3;
    // End of variables declaration//GEN-END:variables
}
