/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user.etalase.aksesoris;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import kaweshop.Kaweshop;

/**
 *
 * @author KWHY
 */
public class anting extends javax.swing.JPanel {

    /**
     * Creates new form anting
     */
    public String id1;
    public String id2;
    public String id3;
    public String nama1;
    public String nama2;
    public String nama3;
    public String harga1;
    public String harga2;
    public String harga3;
    public anting() {
        initComponents();
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 28;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id1 = r.getString("id_barang");
                nama1 = r.getString("nama_barang");
                harga1 = r.getString("harga");
  
                namaanting1.setText(nama1.toUpperCase());
                hargaanting1.setText("Rp."+harga1);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 29;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id2 = r.getString("id_barang");
                nama2 = r.getString("nama_barang");
                harga2 = r.getString("harga");
  
                namaanting2.setText(nama2.toUpperCase());
                hargaanting2.setText("Rp."+harga2);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 30;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id3 = r.getString("id_barang");
                nama3 = r.getString("nama_barang");
                harga3 = r.getString("harga");
  
                namaanting3.setText(nama3.toUpperCase());
                hargaanting3.setText("Rp."+harga3);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel23 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        namaanting3 = new javax.swing.JLabel();
        namaanting1 = new javax.swing.JLabel();
        namaanting2 = new javax.swing.JLabel();
        hargaanting3 = new javax.swing.JTextField();
        hargaanting1 = new javax.swing.JTextField();
        hargaanting2 = new javax.swing.JTextField();
        jumlahanting1 = new javax.swing.JTextField();
        jumlahanting2 = new javax.swing.JTextField();
        jumlahanting3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 77, 168));

        jPanel23.setBackground(new java.awt.Color(42, 186, 237));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blu satir.png"))); // NOI18N
        jPanel23.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel24.setBackground(new java.awt.Color(42, 186, 237));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-earring-colored-gold-bracelet-diamond-earrings-diamond-set-two-tone-gold-earri-5bab7868e05cc0.256375571537964136919.png"))); // NOI18N
        jPanel24.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel25.setBackground(new java.awt.Color(42, 186, 237));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-ruby-earring-jewellery-diamond-gold-diamond-stud-earrings-5ae8fa257028a9.7122595515252178294594.png"))); // NOI18N
        jPanel25.add(jLabel3, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator1.setForeground(new java.awt.Color(42, 186, 237));

        jSeparator2.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator2.setForeground(new java.awt.Color(42, 186, 237));

        jSeparator3.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator3.setForeground(new java.awt.Color(42, 186, 237));

        namaanting3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namaanting3.setForeground(new java.awt.Color(42, 186, 237));
        namaanting3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaanting3.setText("NOT JUST GELANG");

        namaanting1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namaanting1.setForeground(new java.awt.Color(42, 186, 237));
        namaanting1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaanting1.setText("BLU SATIR");

        namaanting2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namaanting2.setForeground(new java.awt.Color(42, 186, 237));
        namaanting2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaanting2.setText("NOT JUST GELANG");

        hargaanting3.setEditable(false);
        hargaanting3.setBackground(new java.awt.Color(16, 77, 168));
        hargaanting3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargaanting3.setForeground(new java.awt.Color(255, 255, 255));
        hargaanting3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        hargaanting1.setEditable(false);
        hargaanting1.setBackground(new java.awt.Color(16, 77, 168));
        hargaanting1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargaanting1.setForeground(new java.awt.Color(255, 255, 255));
        hargaanting1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        hargaanting2.setEditable(false);
        hargaanting2.setBackground(new java.awt.Color(16, 77, 168));
        hargaanting2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargaanting2.setForeground(new java.awt.Color(255, 255, 255));
        hargaanting2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jumlahanting1.setBackground(new java.awt.Color(16, 77, 168));
        jumlahanting1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahanting1.setForeground(new java.awt.Color(255, 255, 255));
        jumlahanting1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jumlahanting2.setBackground(new java.awt.Color(16, 77, 168));
        jumlahanting2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahanting2.setForeground(new java.awt.Color(255, 255, 255));
        jumlahanting2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jumlahanting3.setBackground(new java.awt.Color(16, 77, 168));
        jumlahanting3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahanting3.setForeground(new java.awt.Color(255, 255, 255));
        jumlahanting3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton4.setBackground(new java.awt.Color(16, 77, 168));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(16, 77, 168));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(16, 77, 168));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaanting1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargaanting1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahanting1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(namaanting2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(hargaanting2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahanting2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(namaanting3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargaanting3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahanting3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaanting3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaanting2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaanting1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaanting3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaanting2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaanting1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jumlahanting2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jumlahanting1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jumlahanting3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String jmlhanting1= jumlahanting1.getText();
        int jmlh = Integer.parseInt(jmlhanting1);
        int hrg1 = Integer.parseInt(harga1);
        int totalharga = jmlh * hrg1;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id1);
                p.setString(2, nama1);
                p.setString(3, harga1);
                p.setString(4, jmlhanting1);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String jmlhanting2= jumlahanting2.getText();
        int jmlh = Integer.parseInt(jmlhanting2);
        int hrg2 = Integer.parseInt(harga2);
        int totalharga = jmlh * hrg2;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id2);
                p.setString(2, nama2);
                p.setString(3, harga2);
                p.setString(4, jmlhanting2);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String jmlhanting3= jumlahanting3.getText();
        int jmlh = Integer.parseInt(jmlhanting3);
        int hrg3 = Integer.parseInt(harga3);
        int totalharga = jmlh * hrg3;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id3);
                p.setString(2, nama3);
                p.setString(3, harga3);
                p.setString(4, jmlhanting3);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaanting1;
    private javax.swing.JTextField hargaanting2;
    private javax.swing.JTextField hargaanting3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jumlahanting1;
    private javax.swing.JTextField jumlahanting2;
    private javax.swing.JTextField jumlahanting3;
    private javax.swing.JLabel namaanting1;
    private javax.swing.JLabel namaanting2;
    private javax.swing.JLabel namaanting3;
    // End of variables declaration//GEN-END:variables
}
