/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import user.*;
import user.transaksi.paneltransaksiversi3;
import about.panelabout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import kaweshop.Kaweshop;
import user.etalase.aksesoris.anting;
import user.etalase.baju.jaket;
import user.etalase.aksesoris.cincin;
import user.etalase.aksesoris.gelang;
import user.etalase.baju.kaos;
import user.etalase.baju.kemeja;
import user.etalase.celana.boxer;
import user.etalase.celana.celanapendek;
import user.etalase.celana.jeans;
import user.etalase.mainetalase;
import user.etalase.topi.sombrero;
import user.etalase.topi.topibulat;
import user.etalase.topi.topijeramii;

/**
 *
 * @author KWHY
 */
public class belanjafix extends javax.swing.JFrame {
    
    
    
    //private final panelbaju pb = new panelbaju();

    /**
     * Creates new form belanja
     */
    mainetalase pamain;
    
    kaos pk;
    kemeja pke;
    jaket pj;
    
    celanapendek pc;
    jeans pjea;
    boxer pb;
    
    topibulat pt;
    topijeramii tj;
    sombrero tso;
    
    cincin pa;
    anting pan;
    gelang pg;
    
    panelabout pab;
  
    
    public belanjafix() { 
        initComponents();
        namapembeli.setText(userloginfix.namauser);
        pamain = new mainetalase();
        
        pk = new kaos();
        pke = new kemeja();
        pj = new jaket();
        
        pc = new celanapendek();
        pjea = new jeans();
        pb = new boxer();
        
        pt = new topibulat();
        tj = new topijeramii();
        tso = new sombrero();
        
        pa = new cincin();
        pan = new anting();
        pg = new gelang();
        
        pab = new panelabout();
        
        jPanel3.add(pamain);
        
        jPanel3.add(pk);
        jPanel3.add(pke);
        jPanel3.add(pj);
        
        jPanel3.add(pb);
        jPanel3.add(pc);
        jPanel3.add(pjea);
        
        jPanel3.add(pt);
        jPanel3.add(tj);
        jPanel3.add(tso);
        
        jPanel3.add(pa);
        jPanel3.add(pan);
        jPanel3.add(pg);
        
        jPanel3.add(pab);
        
        pamain.setVisible(true);
        
        pk.setVisible(false);
        pke.setVisible(false);
        pj.setVisible(false);
        
        pc.setVisible(false);
        pjea.setVisible(false);
        pb.setVisible(false);
        
        pt.setVisible(false);
        tj.setVisible(false);
        tso.setVisible(false);
        
        pa.setVisible(false);
        pan.setVisible(false);
        pg.setVisible(false);
        
        pab.setVisible(false);
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        comboaks = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        combotopi = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        combocelana = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        combobaju = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        namapembeli = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 66, 117));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 66, 117));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());

        comboaks.setBackground(new java.awt.Color(0, 66, 117));
        comboaks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comboaks.setForeground(new java.awt.Color(42, 186, 237));
        comboaks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksesoris", "Gelang", "Cincin", "Anting" }));
        comboaks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboaksActionPerformed(evt);
            }
        });
        jPanel6.add(comboaks, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(740, 0, 160, 60);

        jPanel7.setBackground(new java.awt.Color(0, 66, 117));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.BorderLayout());

        combotopi.setBackground(new java.awt.Color(0, 66, 117));
        combotopi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combotopi.setForeground(new java.awt.Color(42, 186, 237));
        combotopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Topi", "Jerami", "Sombrero", "Bulat", " " }));
        combotopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotopiActionPerformed(evt);
            }
        });
        jPanel7.add(combotopi, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(580, 0, 160, 60);

        jPanel8.setBackground(new java.awt.Color(0, 66, 117));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.BorderLayout());

        combocelana.setBackground(new java.awt.Color(0, 66, 117));
        combocelana.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combocelana.setForeground(new java.awt.Color(42, 186, 237));
        combocelana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celana", "Boxer", "Celana Pendek", "Jeans", " " }));
        combocelana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocelanaActionPerformed(evt);
            }
        });
        jPanel8.add(combocelana, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(420, 0, 160, 60);

        jPanel9.setBackground(new java.awt.Color(0, 66, 117));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.BorderLayout());

        combobaju.setBackground(new java.awt.Color(0, 66, 117));
        combobaju.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combobaju.setForeground(new java.awt.Color(42, 186, 237));
        combobaju.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baju", "Kemeja", "Kaos", "Jaket", " " }));
        combobaju.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combobajuFocusGained(evt);
            }
        });
        combobaju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobajuActionPerformed(evt);
            }
        });
        jPanel9.add(combobaju, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(260, 0, 160, 60);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_falcon_32px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 60, 60);

        namapembeli.setBackground(new java.awt.Color(42, 186, 237));
        namapembeli.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namapembeli.setForeground(new java.awt.Color(42, 186, 237));
        namapembeli.setText("Nama");
        jPanel1.add(namapembeli);
        namapembeli.setBounds(80, 10, 110, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 59));

        jPanel2.setBackground(new java.awt.Color(0, 66, 117));
        jPanel2.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_shopping_cart_40px_1.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(850, 10, 40, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(42, 186, 237));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_back_to_32px.png"))); // NOI18N
        jLabel8.setText("Kembali");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 120, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 527, 900, 59));

        jPanel3.setBackground(new java.awt.Color(16, 77, 168));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 468));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, -1, -1));

        setSize(new java.awt.Dimension(900, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        try{
            Connection c = Kaweshop.getkawe();
            String sql = "delete from keranjang";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();   
        }catch(SQLException ex){
            System.out.println("Hapus error");
        }
        new userloginfix().show();
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        pab.setVisible(true);
        pamain.setVisible(false);
        pk.setVisible(false);
        pke.setVisible(false);
        pj.setVisible(false);
            
        pc.setVisible(false);
        pjea.setVisible(false);
        pb.setVisible(false);
  
        pt.setVisible(false);
        tj.setVisible(false);
        tso.setVisible(false);
                        
        pa.setVisible(false);
        pan.setVisible(false);
        pg.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new paneltransaksiversi3().show();
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void combobajuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobajuActionPerformed
        // TODO add your handling code here:
        String baju=combobaju.getSelectedItem().toString();
        if(baju.equals("Baju")){
            pamain.setVisible(true);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
                        
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(baju.equals("Kemeja")){
            pamain.setVisible(false);
            
            pke.setVisible(true);
            pk.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
                        
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(baju.equals("Jaket")){
            pamain.setVisible(false);
            
            pj.setVisible(true);
            pke.setVisible(false);
            pk.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
        
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
                        
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            pab.setVisible(false);
        }
        else if(baju.equals("Kaos")){
            pamain.setVisible(false);
            
            pk.setVisible(true);
            pj.setVisible(false);
            pke.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
            
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
                        
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else{
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
                        
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
    }//GEN-LAST:event_combobajuActionPerformed

    private void combocelanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocelanaActionPerformed
        // TODO add your handling code here:
        String celana=combocelana.getSelectedItem().toString();
        if(celana.equals("Celana")){
            pamain.setVisible(true);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Jeans")){
            pamain.setVisible(false);
            
            pke.setVisible(false);
            pk.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(true);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Boxer")){
            pamain.setVisible(false);
            
            pj.setVisible(false);
            pke.setVisible(false);
            pk.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(true);
        
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Celana Pendek")){
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pj.setVisible(false);
            pke.setVisible(false);
            
            pc.setVisible(true);
            pjea.setVisible(false);
            pb.setVisible(false);
            
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else{
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
    }//GEN-LAST:event_combocelanaActionPerformed

    private void combotopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotopiActionPerformed
        // TODO add your handling code here:
        String celana=combotopi.getSelectedItem().toString();
        if(celana.equals("Topi")){
            pamain.setVisible(true);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Jerami")){
            pamain.setVisible(false);
            
            pke.setVisible(false);
            pk.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(true);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Sombrero")){
            pamain.setVisible(false);
            
            pj.setVisible(false);
            pke.setVisible(false);
            pk.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
        
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(true);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Bulat")){
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pj.setVisible(false);
            pke.setVisible(false);
            
            pc.setVisible(true);
            pjea.setVisible(false);
            pb.setVisible(false);
            
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else{
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
    }//GEN-LAST:event_combotopiActionPerformed

    private void combobajuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combobajuFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combobajuFocusGained

    private void comboaksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboaksActionPerformed
        // TODO add your handling code here:
        String celana=comboaks.getSelectedItem().toString();
        if(celana.equals("Aksesoris")){
            pamain.setVisible(true);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Anting")){
            pamain.setVisible(false);
            
            pke.setVisible(false);
            pk.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(true);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Gelang")){
            pamain.setVisible(false);
            
            pj.setVisible(false);
            pke.setVisible(false);
            pk.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
        
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(true);
            
            pab.setVisible(false);
        }
        else if(celana.equals("Cincin")){
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pj.setVisible(false);
            pke.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
            
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(true);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
        else{
            pamain.setVisible(false);
            
            pk.setVisible(false);
            pke.setVisible(false);
            pj.setVisible(false);
            
            pc.setVisible(false);
            pjea.setVisible(false);
            pb.setVisible(false);
  
            pt.setVisible(false);
            tj.setVisible(false);
            tso.setVisible(false);
            
            pa.setVisible(false);
            pan.setVisible(false);
            pg.setVisible(false);
            
            pab.setVisible(false);
        }
    }//GEN-LAST:event_comboaksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(belanjafix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(belanjafix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(belanjafix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(belanjafix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new belanjafix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboaks;
    private javax.swing.JComboBox<String> combobaju;
    private javax.swing.JComboBox<String> combocelana;
    private javax.swing.JComboBox<String> combotopi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel namapembeli;
    // End of variables declaration//GEN-END:variables
}
