/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user.etalase.baju;

import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import kaweshop.Kaweshop;

/**
 *
 * @author KWHY
 */
public class jaket extends javax.swing.JPanel {

    /**
     * Creates new form jaket
     */
    public String id1;
    public String id2;
    public String id3;
    public String nama1;
    public String nama2;
    public String nama3;
    public String harga1;
    public String harga2;
    public String harga3;
    public jaket() {
        initComponents();
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 4;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id1 = r.getString("id_barang");
                nama1 = r.getString("nama_barang");
                harga1 = r.getString("harga");
  
                namajaket1.setText(nama1.toUpperCase());
                hargajaket1.setText("Rp."+harga1);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 5;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id2 = r.getString("id_barang");
                nama2 = r.getString("nama_barang");
                harga2 = r.getString("harga");
  
                namajaket2.setText(nama2.toUpperCase());
                hargajaket2.setText("Rp."+harga2);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 6;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id3 = r.getString("id_barang");
                nama3 = r.getString("nama_barang");
                harga3 = r.getString("harga");
  
                namajaket3.setText(nama3.toUpperCase());
                hargajaket3.setText("Rp."+harga3);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        namajaket1 = new javax.swing.JLabel();
        namajaket2 = new javax.swing.JLabel();
        namajaket3 = new javax.swing.JLabel();
        hargajaket1 = new javax.swing.JTextField();
        hargajaket2 = new javax.swing.JTextField();
        hargajaket3 = new javax.swing.JTextField();
        jumlahjaket3 = new javax.swing.JTextField();
        jumlahjaket1 = new javax.swing.JTextField();
        jumlahjaket2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 77, 168));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(42, 186, 237));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jaket1.png"))); // NOI18N
        jPanel17.add(jLabel4, java.awt.BorderLayout.CENTER);

        add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 13, 225, 294));

        jPanel18.setBackground(new java.awt.Color(42, 186, 237));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jaket2.png"))); // NOI18N
        jPanel18.add(jLabel5, java.awt.BorderLayout.CENTER);

        add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 13, 225, 294));

        jPanel19.setBackground(new java.awt.Color(42, 186, 237));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/jaket3.png"))); // NOI18N
        jPanel19.add(jLabel6, java.awt.BorderLayout.CENTER);

        add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 13, 225, 294));

        jSeparator1.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator1.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 314, 225, -1));

        jSeparator2.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator2.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 314, 225, -1));

        jSeparator3.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator3.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 314, 225, -1));

        namajaket1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namajaket1.setForeground(new java.awt.Color(42, 186, 237));
        namajaket1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namajaket1.setText("Jaket 1");
        add(namajaket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 323, 225, 29));

        namajaket2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namajaket2.setForeground(new java.awt.Color(42, 186, 237));
        namajaket2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namajaket2.setText("Jaket 2");
        add(namajaket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 323, 225, 29));

        namajaket3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namajaket3.setForeground(new java.awt.Color(42, 186, 237));
        namajaket3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namajaket3.setText("Jaket 3");
        add(namajaket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 323, 225, 29));

        hargajaket1.setBackground(new java.awt.Color(16, 77, 168));
        hargajaket1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargajaket1.setForeground(new java.awt.Color(255, 255, 255));
        hargajaket1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargajaket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 359, 225, 36));

        hargajaket2.setBackground(new java.awt.Color(16, 77, 168));
        hargajaket2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargajaket2.setForeground(new java.awt.Color(255, 255, 255));
        hargajaket2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargajaket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 359, 225, 36));

        hargajaket3.setBackground(new java.awt.Color(16, 77, 168));
        hargajaket3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargajaket3.setForeground(new java.awt.Color(255, 255, 255));
        hargajaket3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargajaket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 359, 225, 36));

        jumlahjaket3.setBackground(new java.awt.Color(16, 77, 168));
        jumlahjaket3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahjaket3.setForeground(new java.awt.Color(255, 255, 255));
        jumlahjaket3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jumlahjaket3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 100, 41));

        jumlahjaket1.setBackground(new java.awt.Color(16, 77, 168));
        jumlahjaket1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahjaket1.setForeground(new java.awt.Color(255, 255, 255));
        jumlahjaket1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jumlahjaket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 100, 41));

        jumlahjaket2.setBackground(new java.awt.Color(16, 77, 168));
        jumlahjaket2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahjaket2.setForeground(new java.awt.Color(255, 255, 255));
        jumlahjaket2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jumlahjaket2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, 41));

        jButton2.setBackground(new java.awt.Color(16, 77, 168));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 40, -1));

        jButton3.setBackground(new java.awt.Color(16, 77, 168));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 40, -1));

        jButton4.setBackground(new java.awt.Color(16, 77, 168));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String jmlhjaket3= jumlahjaket1.getText();
        int jmlh = Integer.parseInt(jmlhjaket3);
        int hrg3 = Integer.parseInt(harga3);
        int totalharga = jmlh * hrg3;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id3);
                p.setString(2, nama3);
                p.setString(3, harga3);
                p.setString(4, jmlhjaket3);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String jmlhjaket1= jumlahjaket1.getText();
        int jmlh = Integer.parseInt(jmlhjaket1);
        int hrg1 = Integer.parseInt(harga1);
        int totalharga = jmlh * hrg1;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id1);
                p.setString(2, nama1);
                p.setString(3, harga1);
                p.setString(4, jmlhjaket1);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String jmlhjaket2= jumlahjaket2.getText();
        int jmlh = Integer.parseInt(jmlhjaket2);
        int hrg2 = Integer.parseInt(harga2);
        int totalharga = jmlh * hrg2;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id2);
                p.setString(2, nama2);
                p.setString(3, harga2);
                p.setString(4, jmlhjaket2);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargajaket1;
    private javax.swing.JTextField hargajaket2;
    private javax.swing.JTextField hargajaket3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jumlahjaket1;
    private javax.swing.JTextField jumlahjaket2;
    private javax.swing.JTextField jumlahjaket3;
    private javax.swing.JLabel namajaket1;
    private javax.swing.JLabel namajaket2;
    private javax.swing.JLabel namajaket3;
    // End of variables declaration//GEN-END:variables
}
