/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user.etalase.baju;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import kaweshop.Kaweshop;

/**
 *
 * @author KWHY
 */
public class kaos extends javax.swing.JPanel {

    /**
     * Creates new form panelbaju
     */
    public String id1;
    public String id2;
    public String id3;
    public String nama1;
    public String nama2;
    public String nama3;
    public String harga1;
    public String harga2;
    public String harga3;
    public kaos() {
        initComponents();
        try{
            Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 1;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id1 = r.getString("id_barang");
                nama1 = r.getString("nama_barang");
                harga1 = r.getString("harga");
                
                namakaos1.setText(nama1.toUpperCase());
                hargakaos1.setText("Rp."+harga1);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 2;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id2 = r.getString("id_barang");
                nama2 = r.getString("nama_barang");
                harga2 = r.getString("harga");
                
                
                namakaos2.setText(nama2.toUpperCase());
                hargakaos2.setText("Rp."+harga2);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 3;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id3 = r.getString("id_barang");
                nama3 = r.getString("nama_barang");
                harga3 = r.getString("harga");
                
                namakaos3.setText(nama3.toUpperCase());
                hargakaos3.setText("Rp."+harga3);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        } 
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        namakaos1 = new javax.swing.JLabel();
        namakaos2 = new javax.swing.JLabel();
        namakaos3 = new javax.swing.JLabel();
        hargakaos3 = new javax.swing.JTextField();
        hargakaos1 = new javax.swing.JTextField();
        hargakaos2 = new javax.swing.JTextField();
        jumlahkaos1 = new javax.swing.JTextField();
        jumlahkaos2 = new javax.swing.JTextField();
        jumlahkaos3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 77, 168));

        jPanel17.setBackground(new java.awt.Color(42, 186, 237));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dbe9a26b73e40a6106a521914c405246.jpg"))); // NOI18N
        jPanel17.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(42, 186, 237));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/028201d74fdc0116cd5de242f6cba052.jpg"))); // NOI18N
        jPanel18.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel19.setBackground(new java.awt.Color(42, 186, 237));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/30ee831f62600f835acf4642960501ed.jpg"))); // NOI18N
        jPanel19.add(jLabel2, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator1.setForeground(new java.awt.Color(42, 186, 237));

        jSeparator2.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator2.setForeground(new java.awt.Color(42, 186, 237));

        jSeparator3.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator3.setForeground(new java.awt.Color(42, 186, 237));

        namakaos1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namakaos1.setForeground(new java.awt.Color(42, 186, 237));
        namakaos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namakaos1.setText("DUDU SHIRT");

        namakaos2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namakaos2.setForeground(new java.awt.Color(42, 186, 237));
        namakaos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namakaos2.setText("MIKO SHIRT");

        namakaos3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namakaos3.setForeground(new java.awt.Color(42, 186, 237));
        namakaos3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namakaos3.setText("RAIDEN SHIRT");

        hargakaos3.setEditable(false);
        hargakaos3.setBackground(new java.awt.Color(16, 77, 168));
        hargakaos3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargakaos3.setForeground(new java.awt.Color(255, 255, 255));
        hargakaos3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        hargakaos1.setEditable(false);
        hargakaos1.setBackground(new java.awt.Color(16, 77, 168));
        hargakaos1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargakaos1.setForeground(new java.awt.Color(255, 255, 255));
        hargakaos1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hargakaos1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hargakaos1FocusGained(evt);
            }
        });
        hargakaos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hargakaos1MouseEntered(evt);
            }
        });
        hargakaos1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                hargakaos1ComponentShown(evt);
            }
        });
        hargakaos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargakaos1ActionPerformed(evt);
            }
        });

        hargakaos2.setEditable(false);
        hargakaos2.setBackground(new java.awt.Color(16, 77, 168));
        hargakaos2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargakaos2.setForeground(new java.awt.Color(255, 255, 255));
        hargakaos2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jumlahkaos1.setBackground(new java.awt.Color(16, 77, 168));
        jumlahkaos1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahkaos1.setForeground(new java.awt.Color(255, 255, 255));
        jumlahkaos1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahkaos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahkaos1ActionPerformed(evt);
            }
        });

        jumlahkaos2.setBackground(new java.awt.Color(16, 77, 168));
        jumlahkaos2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahkaos2.setForeground(new java.awt.Color(255, 255, 255));
        jumlahkaos2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jumlahkaos3.setBackground(new java.awt.Color(16, 77, 168));
        jumlahkaos3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahkaos3.setForeground(new java.awt.Color(255, 255, 255));
        jumlahkaos3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(16, 77, 168));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(16, 77, 168));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(16, 77, 168));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namakaos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargakaos1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahkaos1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2)
                    .addComponent(namakaos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargakaos2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahkaos2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3)
                    .addComponent(namakaos3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hargakaos3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahkaos3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namakaos2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namakaos3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargakaos2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargakaos3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namakaos1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargakaos1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahkaos2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahkaos3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahkaos1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hargakaos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargakaos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargakaos1ActionPerformed

    private void hargakaos1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_hargakaos1ComponentShown

    }//GEN-LAST:event_hargakaos1ComponentShown

    private void hargakaos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargakaos1MouseEntered

    }//GEN-LAST:event_hargakaos1MouseEntered

    private void hargakaos1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hargakaos1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_hargakaos1FocusGained

    private void jumlahkaos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahkaos1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jumlahkaos1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String jmlhkaos2= jumlahkaos2.getText();
        int jmlh2 = Integer.parseInt(jmlhkaos2);
        int hrg2 = Integer.parseInt(harga2);
        int totalharga2 = jmlh2 * hrg2;
        String jmlhharga2 = Integer.toString(totalharga2);
        try{
                Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id2);
                p.setString(2, nama2);
                p.setString(3, harga2);
                p.setString(4, jmlhkaos2);
                p.setString(5, jmlhharga2);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String jmlhkaos1= jumlahkaos1.getText();
        int jmlh = Integer.parseInt(jmlhkaos1);
        int hrg1 = Integer.parseInt(harga1);
        int totalharga = jmlh * hrg1;
        String jmlhharga = Integer.toString(totalharga);
        try{
                Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id1);
                p.setString(2, nama1);
                p.setString(3, harga1);
                p.setString(4, jmlhkaos1);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String jmlhkaos3= jumlahkaos3.getText();
        int jmlh3 = Integer.parseInt(jmlhkaos3);
        int hrg3 = Integer.parseInt(harga3);
        int totalharga2 = jmlh3 * hrg3;
        String jmlhharga3 = Integer.toString(totalharga2);
        try{
                Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES (?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id3);
                p.setString(2, nama3);
                p.setString(3, harga3);
                p.setString(4, jmlhkaos3);
                p.setString(5, jmlhharga3);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargakaos1;
    private javax.swing.JTextField hargakaos2;
    private javax.swing.JTextField hargakaos3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jumlahkaos1;
    private javax.swing.JTextField jumlahkaos2;
    private javax.swing.JTextField jumlahkaos3;
    private javax.swing.JLabel namakaos1;
    private javax.swing.JLabel namakaos2;
    private javax.swing.JLabel namakaos3;
    // End of variables declaration//GEN-END:variables
}
