/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user.etalase.baju;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import kaweshop.Kaweshop;

/**
 *
 * @author KWHY
 */
public class kemeja extends javax.swing.JPanel {

    /**
     * Creates new form kemeja
     */
    public String id1;
    public String id2;
    public String id3;
    public String nama1;
    public String nama2;
    public String nama3;
    public String harga1;
    public String harga2;
    public String harga3;
    public kemeja() {
        initComponents();
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 7;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id1 = r.getString("id_barang");
                nama1 = r.getString("nama_barang");
                harga1 = r.getString("harga");
  
                namakemeja1.setText(nama1.toUpperCase());
                hargakemeja1.setText("Rp."+harga1);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 8;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id2 = r.getString("id_barang");
                nama2 = r.getString("nama_barang");
                harga2 = r.getString("harga");
  
                namakemeja2.setText(nama2.toUpperCase());
                hargakemeja2.setText("Rp."+harga2);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
        try{
            java.sql.Connection c = Kaweshop.getkawe();
            Statement s = c.createStatement();


            String sql = "SELECT * FROM barang where id_barang = 9;";
            ResultSet r = s.executeQuery(sql);
            

           
            while (r.next()){
                id3 = r.getString("id_barang");
                nama3 = r.getString("nama_barang");
                harga3 = r.getString("harga");
  
                namakemeja3.setText(nama3.toUpperCase());
                hargakemeja3.setText("Rp."+harga3);
            }
            
        }catch(SQLException ex){
            System.out.println("Error");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        namakemeja1 = new javax.swing.JLabel();
        namakemeja2 = new javax.swing.JLabel();
        namakemeja3 = new javax.swing.JLabel();
        hargakemeja1 = new javax.swing.JTextField();
        hargakemeja2 = new javax.swing.JTextField();
        hargakemeja3 = new javax.swing.JTextField();
        jumlahkemeja3 = new javax.swing.JTextField();
        jumlahkemeja1 = new javax.swing.JTextField();
        jumlahkemeja2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 77, 168));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(42, 186, 237));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-t-shirt-dress-shirt-check-flannel-button-down-hemd-5b45734235fd70.6561470315312781462212.png"))); // NOI18N
        jPanel17.add(jLabel4, java.awt.BorderLayout.CENTER);

        add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 13, 225, 294));

        jPanel18.setBackground(new java.awt.Color(42, 186, 237));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-t-shirt-flannel-dress-shirt-clothing-checkered-shirt-5b1fb80c6f5428.217567531528805388456.png"))); // NOI18N
        jPanel18.add(jLabel5, java.awt.BorderLayout.CENTER);

        add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 13, 225, 294));

        jPanel19.setBackground(new java.awt.Color(42, 186, 237));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kisspng-t-shirt-sleeve-dress-shirt-fashion-dress-shirt-5ab56db3e2bbb7.4153448815218395399287.png"))); // NOI18N
        jPanel19.add(jLabel6, java.awt.BorderLayout.CENTER);

        add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 13, 225, 294));

        jSeparator1.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator1.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 314, 225, -1));

        jSeparator2.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator2.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 314, 225, -1));

        jSeparator3.setBackground(new java.awt.Color(42, 186, 237));
        jSeparator3.setForeground(new java.awt.Color(42, 186, 237));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 314, 225, -1));

        namakemeja1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namakemeja1.setForeground(new java.awt.Color(42, 186, 237));
        namakemeja1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namakemeja1.setText("Kemeja 1");
        add(namakemeja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 323, 225, 29));

        namakemeja2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namakemeja2.setForeground(new java.awt.Color(42, 186, 237));
        namakemeja2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namakemeja2.setText("Kemeja 2");
        add(namakemeja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 323, 225, 29));

        namakemeja3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        namakemeja3.setForeground(new java.awt.Color(42, 186, 237));
        namakemeja3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namakemeja3.setText("Kemeja 3");
        add(namakemeja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 323, 225, 29));

        hargakemeja1.setBackground(new java.awt.Color(16, 77, 168));
        hargakemeja1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargakemeja1.setForeground(new java.awt.Color(255, 255, 255));
        hargakemeja1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargakemeja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 359, 225, 36));

        hargakemeja2.setBackground(new java.awt.Color(16, 77, 168));
        hargakemeja2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargakemeja2.setForeground(new java.awt.Color(255, 255, 255));
        hargakemeja2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargakemeja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 359, 225, 36));

        hargakemeja3.setBackground(new java.awt.Color(16, 77, 168));
        hargakemeja3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        hargakemeja3.setForeground(new java.awt.Color(255, 255, 255));
        hargakemeja3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(hargakemeja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 359, 225, 36));

        jumlahkemeja3.setBackground(new java.awt.Color(16, 77, 168));
        jumlahkemeja3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahkemeja3.setForeground(new java.awt.Color(255, 255, 255));
        jumlahkemeja3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jumlahkemeja3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 100, 41));

        jumlahkemeja1.setBackground(new java.awt.Color(16, 77, 168));
        jumlahkemeja1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahkemeja1.setForeground(new java.awt.Color(255, 255, 255));
        jumlahkemeja1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jumlahkemeja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 100, 41));

        jumlahkemeja2.setBackground(new java.awt.Color(16, 77, 168));
        jumlahkemeja2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jumlahkemeja2.setForeground(new java.awt.Color(255, 255, 255));
        jumlahkemeja2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jumlahkemeja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, 41));

        jButton3.setBackground(new java.awt.Color(16, 77, 168));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 40, -1));

        jButton4.setBackground(new java.awt.Color(16, 77, 168));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 40, -1));

        jButton5.setBackground(new java.awt.Color(16, 77, 168));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_ok_32px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 40, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String jmlhjaket3= jumlahkemeja3.getText();
        int jmlh = Integer.parseInt(jmlhjaket3);
        int hrg3 = Integer.parseInt(harga3);
        int totalharga = jmlh * hrg3;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id3);
                p.setString(2, nama3);
                p.setString(3, harga3);
                p.setString(4, jmlhjaket3);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String jmlhkemeja1= jumlahkemeja1.getText();
        int jmlh = Integer.parseInt(jmlhkemeja1);
        int hrg1 = Integer.parseInt(harga1);
        int totalharga = jmlh * hrg1;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id1);
                p.setString(2, nama1);
                p.setString(3, harga1);
                p.setString(4, jmlhkemeja1);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String jmlhkemeja2= jumlahkemeja2.getText();
        int jmlh = Integer.parseInt(jmlhkemeja2);
        int hrg2 = Integer.parseInt(harga2);
        int totalharga = jmlh * hrg2;
        String jmlhharga = Integer.toString(totalharga);
        try{
                java.sql.Connection c = Kaweshop.getkawe();
                String sql = "INSERT INTO keranjang VALUES ( ?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, id2);
                p.setString(2, nama2);
                p.setString(3, harga2);
                p.setString(4, jmlhkemeja2);
                p.setString(5, jmlhharga);
                p.executeUpdate();
                p.close();
            }catch(SQLException ex){
                System.out.println("erur");
            }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargakemeja1;
    private javax.swing.JTextField hargakemeja2;
    private javax.swing.JTextField hargakemeja3;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jumlahkemeja1;
    private javax.swing.JTextField jumlahkemeja2;
    private javax.swing.JTextField jumlahkemeja3;
    private javax.swing.JLabel namakemeja1;
    private javax.swing.JLabel namakemeja2;
    private javax.swing.JLabel namakemeja3;
    // End of variables declaration//GEN-END:variables
}
